import React,{useRef,useState} from 'react';
import {Wallet,Ticket,PlusCircle} from 'lucide-react';
import {usePlatform,mutate} from '../../services/journey';
import {DEMO_HERITAGE_TICKETS,demoTicketQuote,SUPER_DEMO_DISCOUNT_PERCENT} from '../../data/superCard';
const money=(paise:number)=>(paise/100).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
export function SuperWallet(){
 const {superWallet=[]}=usePlatform();const balance=superWallet.reduce((sum,r)=>sum+r.amountPaise,0);
 const [amount,setAmount]=useState(2000);const [method,setMethod]=useState('international-card');const [siteId,setSiteId]=useState(DEMO_HERITAGE_TICKETS[0].id);const [visitor,setVisitor]=useState('foreign');const [quantity,setQuantity]=useState(1);const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const pending=useRef<Record<string,string>>({});const quote=demoTicketQuote(siteId,visitor,quantity);
 async function transact(action:'recharge'|'book',body:Record<string,unknown>){
  if(busy)return;setBusy(true);setMessage('');const fingerprint=JSON.stringify([action,body]);
  const requestId=pending.current[fingerprint]||(pending.current[fingerprint]=crypto.randomUUID());
  try{await mutate(`/super-wallet/${action}`,{...body,requestId});delete pending.current[fingerprint];setMessage(action==='recharge'?'Demo balance added. No payment was collected.':'Demo booking saved with your SUPER discount. This is not an admission ticket.');}
  catch(error){setMessage(error instanceof Error?error.message:'Please retry.');}finally{setBusy(false);}
 }
 return <div className="super-wallet"><div className="super-demo-notice"><strong>Demo wallet · no real money</strong><p>Try a visitor wallet for travellers who cannot use local online payment methods. Recharges, ticket prices and the {SUPER_DEMO_DISCOUNT_PERCENT}% member discount are illustrative. No site admission or partner benefit is issued.</p></div>
 <div className="super-wallet-balance"><div><span><Wallet size={19}/>Available demo balance</span><strong>{money(balance)}</strong></div><small>INR wallet · separate from quest points</small></div><p role="status">{message}</p>
 <div className="tourist-two-col"><form className="tourist-quest" onSubmit={e=>{e.preventDefault();transact('recharge',{amount,method});}}><h3><PlusCircle size={20}/>Recharge SUPER card</h3><p>Simulate an international card payment or a staffed cash recharge desk. No payment details are requested.</p><label>Demo recharge amount (₹)<input type="number" min={100} max={20000} step={1} required value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Demo recharge method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="international-card">International card · simulation</option><option value="cash-desk">Cash at visitor desk · simulation</option></select></label><button disabled={busy} type="submit">Add demo balance</button></form>
 <form className="tourist-quest" onSubmit={e=>{e.preventDefault();transact('book',{siteId,visitor,quantity,date});}}><h3><Ticket size={20}/>Heritage tickets</h3><p>Preview a discounted booking paid from your demo wallet.</p><label>Heritage site<select value={siteId} onChange={e=>setSiteId(e.target.value)}>{DEMO_HERITAGE_TICKETS.map(site=><option value={site.id} key={site.id}>{site.name} · {site.city}</option>)}</select></label><label>Visitor category<select value={visitor} onChange={e=>setVisitor(e.target.value)}><option value="foreign">International visitor</option><option value="domestic">Domestic visitor</option></select></label><div className="super-ticket-fields"><label>Visit date<input type="date" min={new Date().toISOString().slice(0,10)} required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Visitors<input type="number" min={1} max={6} step={1} required value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label></div>{quote&&<dl className="super-price"><div><dt>Illustrative ticket price</dt><dd>{money(quote.subtotal)}</dd></div><div><dt>SUPER discount · {SUPER_DEMO_DISCOUNT_PERCENT}% demo</dt><dd>−{money(quote.discount)}</dd></div><div><dt>Pay from demo wallet</dt><dd>{money(quote.total)}</dd></div></dl>}<button disabled={busy||!quote||balance<quote.total} type="submit">{quote&&balance<quote.total?'Recharge demo wallet to book':'Book demo ticket'}</button></form></div>
 <h3>Wallet activity & demo bookings</h3>{!superWallet.length?<p>No wallet activity yet. Start with a demo recharge.</p>:<ul className="super-wallet-activity">{superWallet.slice().reverse().map(entry=><li key={entry.id}><div><strong>{entry.title}</strong><small>{new Date(entry.createdAt).toLocaleString()}{entry.action==='recharge'?` · ${entry.method==='cash-desk'?'Cash desk':'International card'} simulation`:''}</small>{entry.action==='book'&&<><p>{entry.date} · {entry.quantity} visitor{entry.quantity===1?'':'s'} · {entry.visitor==='foreign'?'International':'Domestic'} · Saved {money(entry.discountPaise)}</p><small>DEMO ONLY — not valid for admission · Ref {entry.id.slice(-8).toUpperCase()}</small></>}</div><strong>{entry.amountPaise>0?'+':'−'}{money(Math.abs(entry.amountPaise))}</strong></li>)}</ul>}
 </div>;
}
