import { SuperWallet } from './SuperWallet';
import React,{useState} from 'react';
import {Sparkles,Gift,CheckCircle2,Download} from 'lucide-react';
import {usePlatform,mutate} from '../../services/journey';
import {SUPER_QUESTS,CULTURAL_REWARDS,culturalRewardFile} from '../../data/superCard';
import './tourist.css';
export function SuperCard(){
 const {user,quest,rewards,superWallet=[]}=usePlatform();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [tab,setTab]=useState<'quests'|'wallet'|'rewards'|'history'>('quests');
 const balance=rewards.reduce((sum,r)=>sum+r.points,0);const completed=new Set(quest.filter(q=>q.method==='device-location').map(q=>q.code));
 const walletBalance=superWallet.reduce((sum,r)=>sum+r.amountPaise,0)/100;
 async function checkIn(code:string){
  if(!navigator.geolocation)throw new Error('Location is unavailable on this device. Use a location-enabled browser at the site.');
  const position=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,error=>reject(new Error(error.code===1?'Location permission was denied. Enable it when you are ready to check in.':'Could not locate you. Move outdoors and try again.')),{enableHighAccuracy:true,timeout:20000,maximumAge:0}));
  await mutate('/quest',{code,location:{lat:position.coords.latitude,lng:position.coords.longitude,accuracy:position.coords.accuracy,timestamp:position.timestamp}});
 }
 async function run(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success);}catch(error){setMessage(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 function download(id:string,filename:string){const file=culturalRewardFile(id);const url=URL.createObjectURL(new Blob([file.content],{type:file.type}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="tourist-super" aria-label="SUPER card membership"><div className="tourist-super-face"><div className="tourist-super-top"><span>YATRA ONE MEMBERSHIP</span><Sparkles size={24}/></div><h2>SUPER <span>card</span></h2><p>Visit heritage. Earn points. Travel with one wallet.</p><div className="tourist-super-bottom"><div><strong>{user?.name||'Cultural explorer'}</strong><small>MEMBER · {user?.id?.slice(-8).toUpperCase()}</small></div><div><strong>₹{walletBalance.toLocaleString('en-IN')} <small>DEMO WALLET</small></strong><small>{balance.toLocaleString()} QUEST POINTS</small><small>{SUPER_QUESTS.filter(q=>completed.has(q.code)).length}/{SUPER_QUESTS.length} quests complete</small></div></div></div>
 <div className="tourist-super-content"><nav aria-label="SUPER card sections">{(['quests','wallet','rewards','history'] as const).map(id=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{id==='quests'?'Visit quests':id==='wallet'?'Wallet & tickets':id==='rewards'?'Cultural rewards':'Points history'}</button>)}</nav><p role="status">{message}</p>
 {tab==='wallet'&&<SuperWallet/>}
 {tab==='quests'&&<><p>Earn 10 points by visiting each place and checking in within 300 metres. Each visit quest rewards you once. Location is requested only when you tap Check in; we save the site and completion time, not your precise coordinates.</p><div className="tourist-two-col">{SUPER_QUESTS.map(q=><article className="tourist-quest" key={q.code}><span className="tourist-eyebrow">{completed.has(q.code)?'Visited':`${q.city} · +${q.points} points`}</span><h3>{q.title}</h3><p>{q.description}</p><a className="super-site-link" href={`https://www.google.com/maps/search/?api=1&query=${q.lat},${q.lng}`} target="_blank" rel="noreferrer">View site on map ↗</a>{completed.has(q.code)?<p className="tourist-completed"><CheckCircle2 size={17}/>Visit complete · points collected</p>:<button disabled={busy} onClick={()=>run(()=>checkIn(q.code),'Visit completed — 10 points added to your SUPER card.')}>{busy?'Checking location…':`Check in · ${q.city}`}</button>}</article>)}</div><p className="tourist-muted">Device-location check-ins are a prototype, not official proof of entry. Previous quiz points remain in your history; they do not mark these visits complete.</p></>}
 {tab==='rewards'&&<><h3><Gift size={19}/>Your cultural rewards shop</h3><p>Use points for digital cultural collectibles. No cash value or physical-product redemption.</p><div className="tourist-two-col">{CULTURAL_REWARDS.map(r=>{const owned=rewards.some(entry=>entry.key===r.key&&entry.points<0);return <article className="tourist-quest" key={r.id}><span className="tourist-eyebrow">{owned?'In your collection':`${r.cost} points`}</span><h3>{r.title}</h3><p>{r.description}</p>{owned?<button onClick={()=>download(r.id,r.filename)}><Download size={16}/>Download collectible</button>:<button disabled={busy||balance<r.cost} onClick={()=>run(()=>mutate('/redeem',{rewardId:r.id}),`${r.title} unlocked. Download it from your collection.`)}>{balance<r.cost?`${r.cost-balance} more points needed`:`Redeem ${r.cost} points`}</button>}</article>;})}</div></>}
 {tab==='history'&&<><h3>Points history</h3>{!rewards.length?<p>Your first quest starts your story. Earn points above.</p>:<ul className="tourist-points-history">{rewards.slice().reverse().map(r=><li key={r.id}><span>{r.reason}<small>{new Date(r.createdAt).toLocaleDateString()}</small></span><strong>{r.points>0?'+':''}{r.points}</strong></li>)}</ul>}</>}
 </div></section>;
}
